

package id.co.indocyber.guessgame;

import id.co.indocyber.guessgame.model.WordModel;
import java.util.Arrays;

/**
 *
 * @author user
 */
public class GuessingGame extends javax.swing.JFrame {
    //String basicWord;
    //String [] bankSoal={"Pondok Indah","Sudirman","Tugu Tani","Citos","Gandaria Citty"};
    WordModel modelWorld;
    
    private int jumlah;
    
    WordModel soal1=new WordModel("Pondok Indah","Daerah di Jakarta Selatan");
    WordModel soal2=new WordModel("Grogol","Daerah di Jakarta Barat");
    WordModel soal3=new WordModel("Sudirman","Salah satu nama jalan");
    WordModel soal4=new WordModel("Gandaria","Mall anak muda");
    WordModel soal5=new WordModel("Citos","Mall di Selatan Jakarta");
    WordModel[]bankSoal={soal1,soal2,soal3,soal4,soal5};
    int jumlahKlik=0;
    /**
     * Creates new form GuessingGame
     */
    public GuessingGame() {
        initComponents();
//        basicWord="Buaya darat";

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSoal = new javax.swing.JTextField();
        txtJawaban = new javax.swing.JTextField();
        btnPeriksa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblHasil = new javax.swing.JLabel();
        btnMulai = new javax.swing.JButton();
        btnBantuan = new javax.swing.JButton();
        lblHint = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cPilihan = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tebak Kata");

        txtSoal.setEditable(false);

        btnPeriksa.setText("Periksa");
        btnPeriksa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeriksaActionPerformed(evt);
            }
        });

        jLabel1.setText("Jawaban");

        jLabel2.setText("Soal");

        lblHasil.setText("Belum ada jawaban");

        btnMulai.setText("Mulai");
        btnMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulaiActionPerformed(evt);
            }
        });

        btnBantuan.setText("Bantuan (?)");
        btnBantuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBantuanActionPerformed(evt);
            }
        });

        lblHint.setText("Hint");

        jLabel3.setText("Hint");

        cPilihan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kota" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPeriksa)
                        .addGap(201, 201, 201))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSoal)
                            .addComponent(txtJawaban)
                            .addComponent(lblHint, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cPilihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(btnMulai)
                        .addGap(77, 77, 77)
                        .addComponent(btnBantuan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cPilihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMulai)
                    .addComponent(btnBantuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblHint)
                        .addGap(18, 18, 18)
                        .addComponent(txtSoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJawaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(53, 53, 53)
                .addComponent(btnPeriksa)
                .addGap(59, 59, 59)
                .addComponent(lblHasil)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulaiActionPerformed
        int soalIndex=(int) Math.floor(Math.random()*bankSoal.length);  //Menggunakan floor karena untuk mendapat nilai index 0(nol)
        modelWorld=bankSoal[soalIndex];
        txtSoal.setText(modelWorld.createSoal());
        //basicWord=bankSoal[soalIndex];
        // TODO add your handling code here:
        //Indeks array dimulai dari 0,bukan 1
      
        
//        //Rubah menjadi huruf besar semua
//        basicWord=basicWord.toUpperCase();
//        //Cara 1, rubah String menjadi array String
//        String[]arrayOfWord=basicWord.split("");    //Fungsi split adalah untuk memisahkan bagian bagian dari string
//        //Ketika sudah jadi array, maka sudah memiliki length
//        for(int i=0;i<arrayOfWord.length;i++){
//            System.out.println(arrayOfWord[i]);
//            //Untuk menampilkan array ke 2:
//            System.out.println("Huruf ke 2 : "+arrayOfWord[1]);   
//        }
//        
//        //Cara 2, dengan menjadikan char
//        char[] alphabets=basicWord.toCharArray();
//   
//        int[] bilangan={5,2,13,4};
//        System.out.println("Panjang bilangan : "+bilangan.length);
//        //bilangan[5]=20; //Ini akan menghasilkan error, karena nilai array sudah fix dan panjangnya fix
//                        //Array tidak bisa  ditambhkan panjangnya, kecuali diubah di deklarasi awal
//    
//        
//        //Penggunaan array short
//        Arrays.sort(arrayOfWord);
//        StringBuilder sb=new StringBuilder();
//        
//        System.out.println("\nSetelah disortir\n");
//        for(int i=0;i<arrayOfWord.length;i++){
//           System.out.println(arrayOfWord[i]);            
//            sb.append(arrayOfWord[i]);
//        }String soal=sb.toString();
//        System.out.println("Soal yang harus dijawab : "+soal.trim());
//        txtSoal.setText(soal);
//         
        
    }//GEN-LAST:event_btnMulaiActionPerformed

    private void btnPeriksaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeriksaActionPerformed
        // TODO add your handling code here:
//        jumlahKlik++;
        
        String jawaban=txtJawaban.getText().trim(); //trim untuk tidak menganggap spasi
        modelWorld.setJawaban(jawaban);
        boolean hasil=modelWorld.cekJawaban();
        if(hasil){
           lblHasil.setText("Anda benar");
        }else{
           lblHasil.setText("Coba lagi");
        }
    }//GEN-LAST:event_btnPeriksaActionPerformed

    private void btnBantuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBantuanActionPerformed
        // TODO add your handling code here:
        lblHint.setText(modelWorld.getHint());
    }//GEN-LAST:event_btnBantuanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuessingGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBantuan;
    private javax.swing.JButton btnMulai;
    private javax.swing.JButton btnPeriksa;
    private javax.swing.JComboBox<String> cPilihan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JLabel lblHint;
    private javax.swing.JTextField txtJawaban;
    private javax.swing.JTextField txtSoal;
    // End of variables declaration//GEN-END:variables
}
